#!/bin/sh -e

WITH_MSSIM=0
MSSIM_ARGS=

while [ $# -gt 0 ]; do
        case "$1" in
                --with-mssim)
                        WITH_MSSIM=1
                        shift
                        ;;
                --)
                        shift
                        break
                        ;;
                *)
                        echo "Unrecognized flag $1"
                        exit 1
        esac
done

if [ $WITH_MSSIM -eq 1 ]; then
        MSSIM_ARGS=-use-mssim
fi


go test -v -race ./... -args -check.v $MSSIM_ARGS $@
