name: Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        goversion:
          - 1.18
# The unit tests currently fail against the new stable go
# version (1.24). This needs investigating and resolving,
# but in the meantime, we'll do tests against 1.23.
# See https://github.com/canonical/secboot/issues/383
#         - stable
          - 1.23
    steps:
    - name: Set up Go ${{ matrix.goversion }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.goversion }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y sbsigntool libkeyutils-dev
          sudo snap install core core18
          sudo snap install tpm2-simulator-chrisccoulson
    - name: Build
      run: go build -v
    - name: Test
      run: ./run-tests --with-mssim
    - name: Go vet
      run: go vet
